//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vista.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vista.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icoScriptum {
            get {
                try {
                    object obj = ResourceManager.GetObject("icoScriptum", resourceCulture);
                    if (obj is System.Drawing.Bitmap bmp) return bmp;
                    if (obj is byte[] bytes) return new System.Drawing.Bitmap(new System.IO.MemoryStream(bytes));

                    if (obj == null) {
                        var asm = typeof(Resources).Assembly;
                        string asmName = asm.GetName()?.Name ?? "Vista";
                        string[] candidates = new string[] {
                            asmName + ".Resources.icoScriptum.png",
                            "Vista.Resources.icoScriptum.png"
                        };
                        foreach (var name in candidates) {
                            var stream = asm.GetManifestResourceStream(name);
                            if (stream != null) return new System.Drawing.Bitmap(stream);
                        }
                    }
                }
                catch {
                    // Evitar que el diseñador falle si el recurso no está disponible en diseño.
                }
                return null;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap scriptumlogo {
            get {
                try {
                    object obj = ResourceManager.GetObject("scriptumlogo", resourceCulture);
                    if (obj is System.Drawing.Bitmap bmp) return bmp;
                    if (obj is byte[] bytes) return new System.Drawing.Bitmap(new System.IO.MemoryStream(bytes));

                    if (obj == null) {
                        var asm = typeof(Resources).Assembly;
                        string asmName = asm.GetName()?.Name ?? "Vista";
                        string[] candidates = new string[] {
                            asmName + ".Resources.scriptumlogo.png",
                            "Vista.Resources.scriptumlogo.png"
                        };
                        foreach (var name in candidates) {
                            var stream = asm.GetManifestResourceStream(name);
                            if (stream != null) return new System.Drawing.Bitmap(stream);
                        }
                    }
                }
                catch {
                    // Evitar que el diseñador falle si el recurso no está disponible en diseño.
                }
                return null;
            }
        }

        // Compatibilidad con código que espera 'scriptumLogo' (L may be capitalized).
        internal static System.Drawing.Bitmap scriptumLogo {
            get {
                return scriptumlogo;
            }
        }
    }
}
