// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modelo.Contexto;

#nullable disable

namespace Modelo.Migrations
{
    [DbContext(typeof(Libreria))]
    [Migration("20261002162413_PuntoDeVenta")]
    partial class PuntoDeVenta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AccionGrupo", b =>
                {
                    b.Property<int>("AccionesACC_ID")
                        .HasColumnType("int");

                    b.Property<int>("GruposGRU_ID")
                        .HasColumnType("int");

                    b.HasKey("AccionesACC_ID", "GruposGRU_ID");

                    b.HasIndex("GruposGRU_ID");

                    b.ToTable("AccionGrupo");
                });

            modelBuilder.Entity("AccionUsuario", b =>
                {
                    b.Property<int>("AccionesACC_ID")
                        .HasColumnType("int");

                    b.Property<int>("UsuariosUSU_ID")
                        .HasColumnType("int");

                    b.HasKey("AccionesACC_ID", "UsuariosUSU_ID");

                    b.HasIndex("UsuariosUSU_ID");

                    b.ToTable("AccionUsuario");
                });

            modelBuilder.Entity("GrupoUsuario", b =>
                {
                    b.Property<int>("GruposGRU_ID")
                        .HasColumnType("int");

                    b.Property<int>("UsuariosUSU_ID")
                        .HasColumnType("int");

                    b.HasKey("GruposGRU_ID", "UsuariosUSU_ID");

                    b.HasIndex("UsuariosUSU_ID");

                    b.ToTable("GrupoUsuario");
                });

            modelBuilder.Entity("Modelo.Cliente", b =>
                {
                    b.Property<int>("CLI_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CLI_ID"));

                    b.Property<int>("CLI_PersonaPER_ID")
                        .HasColumnType("int");

                    b.Property<int>("PER_ID")
                        .HasColumnType("int");

                    b.HasKey("CLI_ID");

                    b.HasIndex("CLI_PersonaPER_ID");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Modelo.DetalleVenta", b =>
                {
                    b.Property<int>("DV_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DV_ID"));

                    b.Property<int>("DV_Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("DV_PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LIB_ID")
                        .HasColumnType("int");

                    b.Property<int>("VEN_ID")
                        .HasColumnType("int");

                    b.HasKey("DV_ID");

                    b.HasIndex("LIB_ID");

                    b.HasIndex("VEN_ID");

                    b.ToTable("DetallesVenta");
                });

            modelBuilder.Entity("Modelo.Genero", b =>
                {
                    b.Property<int>("GEN_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GEN_ID"));

                    b.Property<string>("GEN_Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GEN_Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GEN_ID");

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("Modelo.Libro", b =>
                {
                    b.Property<int>("LIB_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LIB_ID"));

                    b.Property<int>("GEN_ID")
                        .HasColumnType("int");

                    b.Property<string>("LIB_Autor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LIB_AñoPublicacion")
                        .HasColumnType("int");

                    b.Property<string>("LIB_Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LIB_Editorial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LIB_ISBN")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("LIB_PrecioVenta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LIB_Stock")
                        .HasColumnType("int");

                    b.Property<string>("LIB_Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LIB_ID");

                    b.HasIndex("GEN_ID");

                    b.HasIndex("LIB_ISBN");

                    b.ToTable("Libros");
                });

            modelBuilder.Entity("Modelo.MetodoPago", b =>
                {
                    b.Property<int>("MP_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MP_ID"));

                    b.Property<bool>("MP_Estado")
                        .HasColumnType("bit");

                    b.Property<string>("MP_Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MP_ID");

                    b.ToTable("MetodosPago");
                });

            modelBuilder.Entity("Modelo.OrdenReposicion", b =>
                {
                    b.Property<int>("OR_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OR_ID"));

                    b.Property<int>("OR_Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("OR_Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OR_Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("OR_LIB_ID")
                        .HasColumnType("int");

                    b.Property<int>("OR_PROV_ID")
                        .HasColumnType("int");

                    b.HasKey("OR_ID");

                    b.HasIndex("OR_LIB_ID");

                    b.HasIndex("OR_PROV_ID");

                    b.ToTable("OrdenesReposicion");
                });

            modelBuilder.Entity("Modelo.PagoVenta", b =>
                {
                    b.Property<int>("PAG_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PAG_ID"));

                    b.Property<int>("MP_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("PAG_Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PAG_Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PAG_Recibido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PAG_Vuelto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VEN_ID")
                        .HasColumnType("int");

                    b.HasKey("PAG_ID");

                    b.HasIndex("MP_ID");

                    b.HasIndex("VEN_ID");

                    b.ToTable("PagosVenta");
                });

            modelBuilder.Entity("Modelo.Proveedor", b =>
                {
                    b.Property<int>("PROV_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PROV_ID"));

                    b.Property<int>("PER_ID")
                        .HasColumnType("int");

                    b.Property<int>("PER_ProveedorPER_ID")
                        .HasColumnType("int");

                    b.Property<string>("PROV_Empresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PROV_ID");

                    b.HasIndex("PER_ProveedorPER_ID");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("Modelo.ProveedorLibro", b =>
                {
                    b.Property<int>("PROV_ID")
                        .HasColumnType("int");

                    b.Property<int>("LIB_ID")
                        .HasColumnType("int");

                    b.Property<decimal>("PL_PrecioCompra")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("PROV_ID", "LIB_ID");

                    b.HasIndex("LIB_ID");

                    b.ToTable("ProveedoresLibros");
                });

            modelBuilder.Entity("Modelo.Seguridad.Accion", b =>
                {
                    b.Property<int>("ACC_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ACC_ID"));

                    b.Property<string>("ACC_Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int?>("FORM_ID")
                        .HasColumnType("int");

                    b.HasKey("ACC_ID");

                    b.HasIndex("FORM_ID");

                    b.ToTable("Acciones");
                });

            modelBuilder.Entity("Modelo.Seguridad.AuditoriaSesion", b =>
                {
                    b.Property<int>("AS_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AS_ID"));

                    b.Property<DateTime>("AS_FechaHoraLogin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AS_FechaHoraLogout")
                        .HasColumnType("datetime2");

                    b.Property<bool>("AS_SesionActiva")
                        .HasColumnType("bit");

                    b.Property<int?>("AS_TiempoSesion")
                        .HasColumnType("int");

                    b.Property<string>("AS_TipoLogout")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AS_USU_ID")
                        .HasColumnType("int");

                    b.Property<int>("AS_UsuarioUSU_ID")
                        .HasColumnType("int");

                    b.HasKey("AS_ID");

                    b.HasIndex("AS_UsuarioUSU_ID");

                    b.ToTable("AuditoriaSesiones");
                });

            modelBuilder.Entity("Modelo.Seguridad.Estado_Grupo", b =>
                {
                    b.Property<int>("EST_GRU_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EST_GRU_ID"));

                    b.Property<string>("EST_GRU_Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("EST_GRU_ID");

                    b.ToTable("Estados_Grupos");
                });

            modelBuilder.Entity("Modelo.Seguridad.Estado_Usuario", b =>
                {
                    b.Property<int>("EST_USU_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EST_USU_ID"));

                    b.Property<string>("EST_USU_Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("EST_USU_ID");

                    b.ToTable("Estados_Usuarios");
                });

            modelBuilder.Entity("Modelo.Seguridad.Formulario", b =>
                {
                    b.Property<int>("FORM_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FORM_ID"));

                    b.Property<string>("FORM_Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int?>("MOD_ID")
                        .HasColumnType("int");

                    b.HasKey("FORM_ID");

                    b.HasIndex("MOD_ID");

                    b.ToTable("Formularios");
                });

            modelBuilder.Entity("Modelo.Seguridad.Grupo", b =>
                {
                    b.Property<int>("GRU_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GRU_ID"));

                    b.Property<int>("EST_GRU_ID")
                        .HasColumnType("int");

                    b.Property<string>("GRU_Descripcion")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("GRU_Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("GRU_ID");

                    b.HasIndex("EST_GRU_ID");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("Modelo.Seguridad.Modulo", b =>
                {
                    b.Property<int>("MOD_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MOD_ID"));

                    b.Property<string>("MOD_Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("MOD_ID");

                    b.ToTable("Modulos");
                });

            modelBuilder.Entity("Modelo.Seguridad.Persona", b =>
                {
                    b.Property<int>("PER_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PER_ID"));

                    b.Property<int>("PER_DNI")
                        .HasColumnType("int");

                    b.Property<string>("PER_Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PER_Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("PER_Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PER_ID");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("Modelo.Seguridad.Usuario", b =>
                {
                    b.Property<int>("USU_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("USU_ID"));

                    b.Property<int?>("EST_USU_ID")
                        .HasColumnType("int");

                    b.Property<int>("PER_ID")
                        .HasColumnType("int");

                    b.Property<string>("USU_Clave")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("USU_Mail")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("USU_Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("USU_PersonaPER_ID")
                        .HasColumnType("int");

                    b.HasKey("USU_ID");

                    b.HasIndex("EST_USU_ID");

                    b.HasIndex("USU_PersonaPER_ID");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Modelo.Venta", b =>
                {
                    b.Property<int>("VEN_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VEN_ID"));

                    b.Property<int>("CLI_ID")
                        .HasColumnType("int");

                    b.Property<int>("MP_ID")
                        .HasColumnType("int");

                    b.Property<decimal>("VEN_AjusteMedioPago")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("VEN_Anulada")
                        .HasColumnType("bit");

                    b.Property<decimal>("VEN_Descuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("VEN_Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VEN_FechaAnulacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("VEN_IVA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VEN_MotivoAnulacion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("VEN_PorcentajeDescuento")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("VEN_Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VEN_Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VEN_Usuario")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VEN_UsuarioAnulacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("VEN_ID");

                    b.HasIndex("CLI_ID");

                    b.HasIndex("MP_ID");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("AccionGrupo", b =>
                {
                    b.HasOne("Modelo.Seguridad.Accion", null)
                        .WithMany()
                        .HasForeignKey("AccionesACC_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelo.Seguridad.Grupo", null)
                        .WithMany()
                        .HasForeignKey("GruposGRU_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccionUsuario", b =>
                {
                    b.HasOne("Modelo.Seguridad.Accion", null)
                        .WithMany()
                        .HasForeignKey("AccionesACC_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelo.Seguridad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuariosUSU_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GrupoUsuario", b =>
                {
                    b.HasOne("Modelo.Seguridad.Grupo", null)
                        .WithMany()
                        .HasForeignKey("GruposGRU_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelo.Seguridad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuariosUSU_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Modelo.Cliente", b =>
                {
                    b.HasOne("Modelo.Seguridad.Persona", "CLI_Persona")
                        .WithMany("Clientes")
                        .HasForeignKey("CLI_PersonaPER_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CLI_Persona");
                });

            modelBuilder.Entity("Modelo.DetalleVenta", b =>
                {
                    b.HasOne("Modelo.Libro", "DV_Libro")
                        .WithMany()
                        .HasForeignKey("LIB_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Modelo.Venta", "DV_Venta")
                        .WithMany("VEN_Detalles")
                        .HasForeignKey("VEN_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DV_Libro");

                    b.Navigation("DV_Venta");
                });

            modelBuilder.Entity("Modelo.Libro", b =>
                {
                    b.HasOne("Modelo.Genero", "LIB_Genero")
                        .WithMany("GEN_Libros")
                        .HasForeignKey("GEN_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LIB_Genero");
                });

            modelBuilder.Entity("Modelo.OrdenReposicion", b =>
                {
                    b.HasOne("Modelo.Libro", "OR_Libro")
                        .WithMany()
                        .HasForeignKey("OR_LIB_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Modelo.Proveedor", "OR_Proveedor")
                        .WithMany()
                        .HasForeignKey("OR_PROV_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OR_Libro");

                    b.Navigation("OR_Proveedor");
                });

            modelBuilder.Entity("Modelo.PagoVenta", b =>
                {
                    b.HasOne("Modelo.MetodoPago", "PAG_MetodoPago")
                        .WithMany()
                        .HasForeignKey("MP_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Modelo.Venta", "PAG_Venta")
                        .WithMany("VEN_Pagos")
                        .HasForeignKey("VEN_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PAG_MetodoPago");

                    b.Navigation("PAG_Venta");
                });

            modelBuilder.Entity("Modelo.Proveedor", b =>
                {
                    b.HasOne("Modelo.Seguridad.Persona", "PER_Proveedor")
                        .WithMany("Profesores")
                        .HasForeignKey("PER_ProveedorPER_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PER_Proveedor");
                });

            modelBuilder.Entity("Modelo.ProveedorLibro", b =>
                {
                    b.HasOne("Modelo.Libro", "PL_Libro")
                        .WithMany("LIB_Proveedores")
                        .HasForeignKey("LIB_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelo.Proveedor", "PL_Proveedor")
                        .WithMany("PROV_Libros")
                        .HasForeignKey("PROV_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PL_Libro");

                    b.Navigation("PL_Proveedor");
                });

            modelBuilder.Entity("Modelo.Seguridad.Accion", b =>
                {
                    b.HasOne("Modelo.Seguridad.Formulario", "Formulario")
                        .WithMany("Acciones")
                        .HasForeignKey("FORM_ID");

                    b.Navigation("Formulario");
                });

            modelBuilder.Entity("Modelo.Seguridad.AuditoriaSesion", b =>
                {
                    b.HasOne("Modelo.Seguridad.Usuario", "AS_Usuario")
                        .WithMany()
                        .HasForeignKey("AS_UsuarioUSU_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AS_Usuario");
                });

            modelBuilder.Entity("Modelo.Seguridad.Formulario", b =>
                {
                    b.HasOne("Modelo.Seguridad.Modulo", "Modulo")
                        .WithMany("Formularios")
                        .HasForeignKey("MOD_ID");

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("Modelo.Seguridad.Grupo", b =>
                {
                    b.HasOne("Modelo.Seguridad.Estado_Grupo", "Estado_Grupo")
                        .WithMany()
                        .HasForeignKey("EST_GRU_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado_Grupo");
                });

            modelBuilder.Entity("Modelo.Seguridad.Usuario", b =>
                {
                    b.HasOne("Modelo.Seguridad.Estado_Usuario", "Estado_Usuario")
                        .WithMany()
                        .HasForeignKey("EST_USU_ID");

                    b.HasOne("Modelo.Seguridad.Persona", "USU_Persona")
                        .WithMany("Usuarios")
                        .HasForeignKey("USU_PersonaPER_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado_Usuario");

                    b.Navigation("USU_Persona");
                });

            modelBuilder.Entity("Modelo.Venta", b =>
                {
                    b.HasOne("Modelo.Cliente", "VEN_Cliente")
                        .WithMany()
                        .HasForeignKey("CLI_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Modelo.MetodoPago", "VEN_MetodoPago")
                        .WithMany()
                        .HasForeignKey("MP_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VEN_Cliente");

                    b.Navigation("VEN_MetodoPago");
                });

            modelBuilder.Entity("Modelo.Genero", b =>
                {
                    b.Navigation("GEN_Libros");
                });

            modelBuilder.Entity("Modelo.Libro", b =>
                {
                    b.Navigation("LIB_Proveedores");
                });

            modelBuilder.Entity("Modelo.Proveedor", b =>
                {
                    b.Navigation("PROV_Libros");
                });

            modelBuilder.Entity("Modelo.Seguridad.Formulario", b =>
                {
                    b.Navigation("Acciones");
                });

            modelBuilder.Entity("Modelo.Seguridad.Modulo", b =>
                {
                    b.Navigation("Formularios");
                });

            modelBuilder.Entity("Modelo.Seguridad.Persona", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Profesores");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Modelo.Venta", b =>
                {
                    b.Navigation("VEN_Detalles");

                    b.Navigation("VEN_Pagos");
                });
#pragma warning restore 612, 618
        }
    }
}
